// src/sections/ContactSection.tsx
import { Mail, Slack, Github } from "lucide-react";
import { Card } from "../components/ui";

export default function ContactSection() {
    return (
        <Card className="border-slate-200 dark:border-slate-700">
            <div className="p-4 space-y-3">
                <header className="space-y-3 pb-4 border-b border-slate-200 dark:border-slate-700">
                    <h2 className="text-lg font-semibold">お問合せ</h2>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">
                        困ったときはこちらからお問い合わせください。返信目安: 平日1〜3日
                    </p>
                </header>

                <div className="space-y-2">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="h-8 w-8 rounded-md bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-400 flex items-center justify-center border border-indigo-100 dark:border-indigo-800">
                                <Mail className="h-4 w-4" />
                            </div>
                            <div>
                                <div className="font-semibold">メール</div>
                                <div className="text-xs text-slate-500 dark:text-slate-400">
                                    Ibaragiakira2007@gmail.com
                                </div>
                            </div>
                        </div>
                        <a
                            href="mailto:Ibaragiakira2007@gmail.com"
                            className="text-xs text-slate-500 dark:text-slate-400"
                            aria-label="メールを開く（Ibaragiakira2007@gmail.com）"
                        >
                            開く
                        </a>
                    </div>

                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="h-8 w-8 rounded-md bg-slate-50 dark:bg-slate-700 text-slate-700 dark:text-slate-300 flex items-center justify-center border border-slate-100 dark:border-slate-600">
                                <Slack className="h-4 w-4" />
                            </div>
                            <div>
                                <div className="font-semibold">Slack</div>
                                <div className="text-xs text-slate-500 dark:text-slate-400">Prason</div>
                            </div>
                        </div>
                        <a
                            href="https://n-highschool.slack.com/team/U04VDPX7ZHV"
                            className="text-xs text-slate-500 dark:text-slate-400"
                            target="_blank"
                            rel="noopener noreferrer"
                            aria-label="Slack を開く（n-highschool.slack.com）"
                        >
                            開く
                        </a>
                    </div>

                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="h-8 w-8 rounded-md bg-slate-50 dark:bg-slate-700 text-slate-700 dark:text-slate-300 flex items-center justify-center border border-slate-100 dark:border-slate-600">
                                <Github className="h-4 w-4" />
                            </div>
                            <div>
                                <div className="font-semibold">GitHub</div>
                                <div className="text-xs text-slate-500 dark:text-slate-400">narcissus-tazetta</div>
                            </div>
                        </div>
                        <a
                            href="https://github.com/narcissus-tazetta"
                            className="text-xs text-slate-500 dark:text-slate-400"
                            target="_blank"
                            rel="noopener noreferrer"
                            aria-label="GitHub を開く（narcissus-tazetta）"
                        >
                            開く
                        </a>
                    </div>
                </div>
            </div>
        </Card>
    );
}

// src/lib/sections/ContactSection.svelte
<script lang="ts">
    import { Mail } from "@lucide/svelte";
    import SlackIcon from "$lib/icons/SlackIcon.svelte";
    import GithubIcon from "$lib/icons/GithubIcon.svelte";

    const contacts = [
        {
            icon: Mail,
            label: "メール",
            value: "Ibaragiakira2007@gmail.com",
            href: "mailto:Ibaragiakira2007@gmail.com",
            external: false,
            tint: "bg-indigo-50 text-indigo-700 border-indigo-100 dark:bg-indigo-900/30 dark:text-indigo-400 dark:border-indigo-800",
        },
        {
            icon: SlackIcon,
            label: "Slack",
            value: "Prason",
            href: "https://n-highschool.slack.com/team/U04VDPX7ZHV",
            external: true,
            tint: "bg-slate-50 text-slate-700 border-slate-100 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-600",
        },
        {
            icon: GithubIcon,
            label: "GitHub",
            value: "narcissus-tazetta",
            href: "https://github.com/narcissus-tazetta",
            external: true,
            tint: "bg-slate-50 text-slate-700 border-slate-100 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-600",
        },
    ];
</script>

<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
    <header class="mb-4 space-y-1 border-b border-slate-200 pb-4 dark:border-slate-800">
        <h2 class="text-lg font-semibold text-slate-900 dark:text-slate-100">お問合せ</h2>
        <p class="text-sm text-slate-500 dark:text-slate-400">
            困ったときはこちらからお問い合わせください。返信目安: 平日1〜3日
        </p>
    </header>

    <div class="space-y-1">
        {#each contacts as contact (contact.label)}
            {@const Icon = contact.icon}
            <a
                href={contact.href}
                target={contact.external ? "_blank" : undefined}
                rel={contact.external ? "noopener noreferrer" : undefined}
                class="flex items-center justify-between rounded-lg px-2 py-2 transition-colors hover:bg-slate-50 dark:hover:bg-slate-800/60"
                aria-label="{contact.label} を開く（{contact.value}）"
            >
                <span class="flex items-center gap-3">
                    <span class="flex h-8 w-8 items-center justify-center rounded-md border {contact.tint}">
                        <Icon class="h-4 w-4" />
                    </span>
                    <span>
                        <span class="block text-sm font-semibold text-slate-900 dark:text-slate-100"
                            >{contact.label}</span
                        >
                        <span class="block text-xs text-slate-500 dark:text-slate-400">{contact.value}</span>
                    </span>
                </span>
                <span class="text-xs text-slate-400 dark:text-slate-500">開く</span>
            </a>
        {/each}
    </div>
</div>
